Update `sync-all` and others files w.r.t. merged testsuite (re #8545)
See merge commit 66693401b98cb5aa912948af7bbd2182474f50c4

This commit also adds a check for a left-over testsuite/.git folder to sync-all

This way, the first time sync-all is called after updating to a
post-testsuite-merge (see #8545) state of ghc.git, the sync-all script
aborts with an error message if a `testsuite/.git` folder is detected and
thus forces the user to take action.

Signed-off-by: Herbert Valerio Riedel <hvr@gnu.org>

diff --git a/validate b/validate
--- a/validate
+++ b/validate
@@ -89,8 +89,7 @@ check_packages () {
 
 if ! [ -d testsuite ]
 then
-    echo 'You need the testsuite to validate' >&2
-    echo 'Run "./sync-all --testsuite get" to get it' >&2
+    echo 'Could not find the testsuite for validation' >&2
     exit 1
 fi
 
