Check for cabal-install >= 3.12 upfront
Starting with commit 8cb99552f607f6bc4000e45ab32532d50c8bb996, Hadrian
requires cabal-install >= 3.12 in order to use the 'cabal path' command
that was introduced in version 3.12, as per
  https://github.com/haskell/cabal/blob/a51c4ee1556d816ad86e90db7e6330dd51b0b6e7/release-notes/cabal-install-3.12.1.0.md?plain=1#L45

This was not reflected in the Hadrian build script, causing a delayed
build failure instead of enforcing the version requirement upfront,
which this patch does.

Fixes #27317

diff --git a/hadrian/build-cabal b/hadrian/build-cabal
--- a/hadrian/build-cabal
+++ b/hadrian/build-cabal
@@ -23,8 +23,10 @@ fi
 CABVERSTR=$("$CABAL" --numeric-version)
 CABVER=( ${CABVERSTR//./ } )
 
-if [ "${CABVER[0]}" -lt 3 ]; then
-    echo "Cabal version is too old; you need at least cabal-install 3.0"
+# We use 'cabal path', introduced with cabal-install 3.12.
+# Check version ahead of time to avoid a surprising failure later (#27317).
+if [ "${CABVER[0]}" -lt 3 ] || { [ "${CABVER[0]}" -eq 3 ] && [ "${CABVER[1]}" -lt 12 ]; }; then
+    echo "Cabal version is too old; you need at least cabal-install 3.12"
     exit 2
 fi
 
